# Generated by Django 5.0.4 on 2024-04-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='task_type',
            new_name='pending',
        ),
        migrations.RenameField(
            model_name='usertask',
            old_name='task_detail',
            new_name='taskdetails',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='task_email',
        ),
        migrations.AddField(
            model_name='usertask',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
